_dataset:
  type: TartanairDataset
  params:
    split_file: data_splits/tartanair/train_part.txt
    full_size: [480, 640]
    patch_size: null
    random_resize: True
    normalize_params: [0, 0, 0]
    flip_mode: k
    color_aug: True
    output_frame: ['o']
    multi_out_scale: [3,2,1]
    load_KTmatrix: True
    load_depth: True
    load_depthhints: False
    is_fixK: True
    stereo_test: False
    jpg_test: False
    improved_test: False